{% set version = "0.3.0" %}

package:
    name: cell_tree2d
    version: {{ version }}

source:
    fn: cell_tree2d-{{ version }}-.tar.gz
    url: https://github.com/NOAA-ORR-ERD/cell_tree2d/archive/v{{ version }}.tar.gz
    sha256: 1732d82316c6df5e36dbee517afcb4530b4fed80eb3c9c4ef297c5a9c9dac85e

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x

test:
    requires:
        - pytest
    imports:
        - cell_tree2d
    commands:
        - py.test --pyargs cell_tree2d
        - conda inspect linkages -n _test cell_tree2d  # [linux]

about:
    home: https://github.com/NOAA-ORR-ERD/cell_tree2d
    license: Public Domain
    summary: CellTree data structure as described by Garth and Joy 2010

extra:
    recipe-maintainers:
        - ocefpaf
        - ChrisBarker-NOAA
        - jay-hennen 
        
