travis:
  secure:
    BINSTAR_TOKEN: AjWIwKXYGMcCgX6NdMT3mfZhoqC0FY7+JxdjQfa7BKLJMNMzrSMsbjMlzUgjL1Xqh5SLNWuZTYkKRHnw3kqxLGaKdPXImuMa9eO1bQ0Ly68f9Oi1byQ+PA4G8/ELM8JB5a2Xwe6eEmaK9aVcnBi/6OrvGpbN4jb5l6Q37Uz0T22S5MoWlrIHlqw0PGD2XORh2YTYEPDuX2jQZ6NRvE0nMc+k6ZvBhG/+KeSZJZT24D1Mt1I8b0nGBPcaUC4lVxhDPyPYuas4zhD2Y5oBpZ4/cMxxMFB7gtteDzoK9WuBBlZ6zNyaE68Ae6OUHZcR+toOUjurFOFC1Rk9CTfbCTzgd1tXjo83pBhHw/9JX4V5JvqzoEo7L9JwECVtCDSkCPmz9eatLtmt2fHYNnij61oZGkKtPCcd3WjEkoHKv/7Obi+CJraXkxuLR/cyj0OLoYgHz9LTpsUJmjAm6axUX/VKvgzIIS7WX2rnmu8rZq5Tc1s4MtRsD5Hz5COnKJa4kBRQWzSfAJKq9/nTSpC//IOqwKE0XWe+6ivDAlbm5v9xDRMcHfb+WWQBAy+5UxQMRJrxnXFkI/N/PgJyd2PglkbbY0hj2lwtPonZORSsYmt0KiH2Jhr9LFSfDZozbi06imkLH6dvd8oSIN1rkQH/4EwyABbyPLb09mnICQgb6/1Mlds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
