travis:
  secure:
    BINSTAR_TOKEN: tyDjQ6mVruV/OYsOYzJ4gZHrzq+WsFVtnuCXxhJ/idq/qOqI73tMax+hSqyGfaKaisJOF9H0uIl3M+PzeIY8+aqc0ASo6/4BtCtzQ2Q8egSBjUt3rv3MqSd2V/7cd2Zb8yuO08KB7U5phuhyk4Oc3j4JEclbcNVX+kR2kVxc+9xi0zQJe1hIagNwq9J9LUsdu9ssQFh2eSK7Rfh4dob1wEFO4A52XWAH5nFXKgZOsR3CW819n9V16MtlzMIpuXvTG8I0QU2HpQ4ZWoWov8+9qZA7T2y1clCCfktagbsistJVUN9AtMYf3nqW8KOazAP3kC8CUPQwn8USL6KGCiwDfILDzjcCWWRbPyQjGwiDYmPnbD9qT2VdfRAF+CXJ3glF/pu9yKmyhVMb7cItwCEAEHfVdKUMtlxZq2tVPgQu/6WZ+75TlugH3COqnIobeJ5lRrEAXbRNWMmFZIVAB69OTYDojGYZRlss2dxm1bRUKmrgh9dFXr4bXyoHP95oIN5BA3bohW7i361fFhYkODbIx3mO3WmlsXuFZtv1nFJyHYaYApxMxO8Y9FjaeUw7RWhLFNeYSuBP+YScnRvEIMBpqVRNJpZtUq/XIeLIBTXGW8z67E4ujbdzddfBOipMlFn19lbVXSr6X6wWhbPZoMhKIXoJdEyRaw3OzecFZKqHDx4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
